default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: coding_interview_development

test:
  <<: *default
  database: coding_interview_test

production:
  <<: *default
  database: coding_interview_production